name: Build Super Email
on:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        # Perintah ini akan menjalankan npm install lalu otomatis menjalankan postinstall
        run: npm install

      - name: Build Electron App
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Super-Email-${{ matrix.os }}
          path: |
            dist/*.exe
            dist/*.dmg